name:                umberto
version:             0.1.0.0
github:              "trailofbits/umberto"
license:             BSD3
author:              "JP Smith"
maintainer:          "jp@trailofbits.com"
copyright:           "2019 JP Smith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/umberto#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib
  dependencies:
    - binary
    - bytestring
    - constraints
    - lens
    - mtl
    - process
    - process-extras
    - QuickCheck
    - template-haskell
    - random
    - random-fu
    - tardis
    - template-haskell
    - tostring

executables:
  umberto-mutate:
    source-dirs: src
    main: Main.hs
    dependencies:
      - umberto
      - aeson
      - asn1-encoding
      - asn1-types
      - bytestring
      - containers
      - constraints
      - lens
      - optparse-applicative
      - QuickCheck
      - quickcheck-instances
      - xml
